name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: oussamf/carthagians

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          commit_message: Deploy from GitHub Actions
          commit_user_name: GitHub Actions
          commit_email: actions@github.com
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: latest
