name: Two-Approval Workflow
on:
  pull_request:
    branches:
      - main
    reviewers:
      - oussamf1
      - Ahmed0-0Kallel
      - haouetya
      - DinaBouallegui
      - Iheb-JB

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  approval:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Approval from Member 1
        uses: reviewdog/action-approve@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_review_body: "Member 1 approves this PR"
          review_event: "APPROVE"
      - name: Approval from Member 2
        uses: reviewdog/action-approve@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_review_body: "Member 2 approves this PR"
          review_event: "APPROVE"
